export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CLEAR_USER_MESSAGE = 'CLEAR_USER_MESSAGE';
export const CLEAR_EMPLOYEE_MESSAGE = 'CLEAR_EMPLOYEE_MESSAGE';

export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';
export const CLEAR_EMPLOYEE_ERROR = 'CLEAR_EMPLOYEE_ERROR';

export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAIL = 'GET_EMPLOYEES_FAIL';

export const GET_EMPLOYEE_DETAILS_SUCCESS = 'GET_EMPLOYEE_DETAILS_SUCCESS';
export const GET_EMPLOYEE_DETAILS_FAIL = 'GET_EMPLOYEE_DETAILS_FAIL';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const USER_ERROR = 'USER_ERROR';

export const PROMPT_2FA_VERIFICATION = 'PROMPT_2FA_VERIFICATION';