import React, { useEffect, useState } from "react";
import SecurityLock from "../assets/security-safety-lock-icon-vector-45499329-removebg-preview.png";
import { useDispatch, useSelector } from "react-redux";
import { verify2FA } from "../redux/actions/authActions";
import { useNavigate } from "react-router-dom";

function TwoFaVarification() {
  const dispatch = useDispatch();
  const { error, isAuthenticated, authUser } = useSelector((state) => state.auth); 
  const [code, setCode] = useState("");
  const navigate = useNavigate()

  useEffect(() => {
    if (isAuthenticated) {
      navigate("/");
    }
  }, [isAuthenticated, navigate]);

  console.log(`auth users`, authUser)

  const handleSubmit = (e) => {
    e.preventDefault();
    dispatch(verify2FA(authUser?.email, code, navigate));
  };

  const handleCancel = () => {
    setCode(""); 
  };

  return (
    <div className="w-screen h-screen flex items-center justify-center">
      <div className="absolute flex items-center justify-center px-4 top-10 left-8">
        <div className="w-8 h-8 bg-indigo-600 rounded-full flex items-center justify-center">
          <span className="font-pop text-white font-bold text-xl">IT</span>
        </div>
        <span className="ml-2 font-pop text-blue-700 font-bold text-lg tracking-wide">
          SOLUTION
        </span>
      </div>
      <div className="max-w-md min-h-[350px] border-2 border-slate-300 rounded-md p-6 mx-3">
        <form onSubmit={handleSubmit} className="flex flex-col gap-2 items-center">
          <h1 className="text-2xl text-center">Two-factor authentication</h1>
          <p className="text-center">
            Enter the 6-digit code generated by your authentication app.
          </p>
          <div className="">
            <img className="w-40 h-40 mx-auto" src={SecurityLock} alt="Security Lock" />
          </div>
          <input
            onChange={(e) => setCode(e.target.value)}
            value={code}
            type="text"
            className="border-2 border-slate-400 rounded-md p-2 max-w-[220px]"
            placeholder="Enter code"
          />
          <div className="flex gap-2">
            <button type="submit" className="bg-primary text-white rounded-md px-4 py-2 mt-4">
              Verify
            </button>
            <button type="button" onClick={handleCancel} className="bg-gray-300 text-white rounded-md px-4 py-2 mt-4">
              Cancel
            </button>
          </div>
        </form>
        {/* Error Message */}
        {error && <p className="text-red-500 text-sm mb-4 mt-4 text-center">{error}</p>}
      </div>
    </div>
  );
}

export default TwoFaVarification;
